<?php
function stm_theme_options_restaurant()
{
	$json = '{
  "post_layout": "9",
  "post_sidebar": "false",
  "post_sidebar_archive_mobile": "hidden",
  "post_sidebar_position": "left",
  "post_view": "list",
  "post_author": "false",
  "post_comments": "true",
  "post_image": "true",
  "post_info": "true",
  "post_share": "false",
  "post_sidebar_single": "false",
  "post_sidebar_single_position": "left",
  "post_tags": "true",
  "post_title": "false",
  "main_color": "#ce9933",
  "secondary_color": "#ce9933",
  "third_color": "#274253",
  "copyright":"Pearl Theme by <a href=\"https:\/\/themeforest.net\/item\/pearl-true-multiniche-wordpress-theme\/20432158\" target=\"_blank\">Stylemix Themes.<\/a>",
  "copyright_co": "true",
  "copyright_socials": "true",
  "copyright_year": "true",
  "footer_bottom_bg": "",
  "right_text": "",
  "footer_socials": "",
  "footer_bg": "#ffffff",
  "footer_bg_image": "",
  "footer_color": "#000000",
  "footer_cols": "4",
  "accordions_style": "style_4",
  "buttons_global_style": "style_9",
  "currency_symbol": "$",
  "currency_symbol_position": "left",
  "forms_global_style": "style_8",
  "boxed": "false",
  "boxed_bg": "",
  "enable_ajax": "false",
  "ga": "",
  "google_maps_api": "",
  "site_padding": "0",
  "site_width": "1340",
  "google_api_key": "",
  "favicon": "",
  "logo": "4287",
  "logo_transparent": "",
  "logo_width": "196",
  "pagination_style": "style_9",
  "paypal_currency_code": "USD",
  "paypal_email": "timur@stylemix.net",
  "paypal_mode": "sandbox",
  "preloader": "true",
  "preloader_color": "#ce9933",
  "sidebars_global_style": "style_9",
  "tabs_style": "style_4",
  "page_title_box": "true",
  "page_title_box_align": "center",
  "page_title_box_bg_color": "rgba(38, 44, 47, 0.5)",
  "page_title_box_bg_image": "9",
  "page_title_box_override": "false",
  "page_title_box_style": "style_9",
  "page_title_box_subtitle": "\u2666",
  "page_title_box_subtitle_color": "#ffffff",
  "page_title_box_text_color": "#ffffff",
  "page_title_box_title": "",
  "page_title_box_title_size": "h1",
  "page_title_breadcrumbs": "false",
  "page_title_button": "false",
  "page_title_button_text": "",
  "page_title_button_url": "",
  "tour_style": "style_3",
  "bottom_bar_bg": "",
  "bottom_bar_bottom": "0",
  "bottom_bar_color": "#f00",
  "bottom_bar_link_colorhover": "#f00",
  "bottom_bar_text_color": "#f00",
  "bottom_bar_top": "0",
  "header_builder": {
    "center": {
      "center": [
        {
          "$$hashKey": "object:440",
          "data": {
            "divider": "icon",
            "dividerIcon": "stmicon-bon_appetit_diamond",
            "dividerSymbol": "&diams;",
            "fixedHeader": {
              "mobile": "true"
            },
            "font": "mf",
            "fsz": "16",
            "id": "30",
            "style": "default"
          },
          "disabled": {
            "default": "",
            "mobile": "",
            "tablet": ""
          },
          "label": "Menu",
          "margins": {
            "default": {
              "top": "90"
            }
          },
          "order": {
            "mobile": "1200",
            "tablet": "1200"
          },
          "position": [
            "center",
            "center",
            "0"
          ],
          "type": "menu"
        }
      ]
    }
  },
  "center_header_fullwidth": "false",
  "header_bg": "",
  "header_bg_fill": "full",
  "header_bottom": "0",
  "header_color": "rgba(0, 0, 0, 0.8)",
  "header_text_color": "#ffffff",
  "header_text_color_hover": "#ce9933",
  "header_top": "0",
  "header_socials": "",
  "main_header_offset": "false",
  "main_header_sticky_mobile": "true",
  "main_header_style": "style_9",
  "main_header_transparent": "true",
  "top_bar_bg": "",
  "top_bar_bottom": "0",
  "top_bar_color": "#f00",
  "top_bar_link_color_hover": "#f00",
  "top_bar_text_color": "#f00",
  "top_bar_top": "0",
  "page_bc": "false",
  "page_bc_fullwidth": "false",
  "coming_soon_style": "style_1",
  "error_page_bg": "4273",
  "error_page_style": "style_6",
  "albums": {
    "enabled": "false"
  },
  "divider_mus_1": "",
  "stm_albums_sidebar_single": "default",
  "stm_albums_sidebar_single_mobile": "hidden",
  "stm_albums_sidebar_single_position": "left",
  "divider_donations_1": "",
  "divider_donations_2": "",
  "divider_donations_3": "",
  "donations": {
    "enabled": "false"
  },
  "stm_donations_amount_1": "10",
  "stm_donations_amount_2": "20",
  "stm_donations_amount_3": "30",
  "stm_donations_layout": "1",
  "stm_donations_sidebar": "default",
  "stm_donations_sidebar_position": "left",
  "stm_donations_sidebar_single": "default",
  "stm_donations_sidebar_single_mobile": "hidden",
  "stm_donations_sidebar_single_position": "left",
  "stm_donations_view": "list",
  "divider_events_1": "",
  "divider_events_2": "",
  "events": {
    "enabled": "false"
  },
  "stm_events_layout": "left",
  "stm_events_sidebar": "default",
  "stm_events_sidebar_position": "left",
  "stm_events_sidebar_single": "default",
  "stm_events_sidebar_single_mobile": "hidden",
  "stm_events_sidebar_single_position": "left",
  "stm_events_view": "list",
  "divider_projects_1": "",
  "divider_projects_2": "",
  "projects": {
    "enabled": "false"
  },
  "stm_projects_sidebar": "default",
  "stm_projects_sidebar_position": "left",
  "stm_projects_sidebar_single": "default",
  "stm_projects_sidebar_single_mobile": "hidden",
  "stm_projects_sidebar_single_position": "left",
  "stm_projects_view": "grid",
  "divider_services_1": "",
  "divider_services_2": "",
  "stm_services_layout": "left",
  "stm_services_sidebar": "default",
  "stm_services_sidebar_position": "left",
  "stm_services_sidebar_single": "default",
  "stm_services_sidebar_single_mobile": "hidden",
  "stm_services_sidebar_single_position": "left",
  "stm_stories_layout": "left",
  "stm_stories_sidebar_single": "default",
  "stm_stories_sidebar_single_mobile": "hidden",
  "stm_stories_sidebar_single_position": "left",
  "stories": {
    "enabled": "false"
  },
  "divider_vac_1": "",
  "stm_vacancies_button": "true",
  "stm_vacancies_button_text": "",
  "stm_vacancies_button_url": "",
  "stm_vacancies_details": "true",
  "stm_vacancies_layout_single": "left",
  "stm_vacancies_share": "true",
  "stm_vacancies_sidebar_single": "default",
  "stm_vacancies_sidebar_single_mobile": "hidden",
  "stm_vacancies_sidebar_single_position": "left",
  "vacancies": {
    "enabled": "false"
  },
  "divider_vid_1": "",
  "stm_videos_sidebar_single": "default",
  "stm_videos_sidebar_single_mobile": "hidden",
  "stm_videos_sidebar_single_position": "left",
  "videos": {
    "enabled": "true"
  },
  "shop_items": "3",
  "product_sidebar": "default",
  "product_sidebar_position": "left",
  "blockquote_style": "style_6",
  "body_font": {
    "color": "#000000",
    "fw": "400",
    "ln": "24",
    "ls": "0",
    "mgb": "",
    "name": "Quicksand",
    "size": "16"
  },
  "h1_settings": {
    "color": "#274253",
    "fw": "400",
    "ln": "60",
    "ls": "0",
    "mgb": "50",
    "name": "Kaushan Script",
    "size": "60"
  },
  "h2_settings": {
    "color": "#274253",
    "fw": "400",
    "ln": "50",
    "ls": "0",
    "mgb": "45",
    "name": "Kaushan Script",
    "size": "50"
  },
  "h3_settings": {
    "color": "#274253",
    "fw": "700",
    "ln": "28",
    "ls": "0",
    "mgb": "50",
    "name": "Quicksand",
    "size": "28"
  },
  "h4_settings": {
    "color": "#274253",
    "fw": "400",
    "ln": "24",
    "ls": "0",
    "mgb": "35",
    "name": "Quicksand",
    "size": "24"
  },
  "h5_settings": {
    "color": "#274253",
    "fw": "700",
    "ln": "18",
    "ls": "0",
    "mgb": "30",
    "name": "Quicksand",
    "size": "18"
  },
  "h6_settings": {
    "color": "#274253",
    "fw": "700",
    "ln": "16",
    "ls": "0",
    "mgb": "25",
    "name": "Quicksand",
    "size": "16"
  },
  "headings_line": "false",
  "headings_line_height": "5",
  "headings_line_position": "top",
  "headings_line_width": "45",
  "secondary_font": {
    "color": "",
    "name": "Kaushan Script",
    "subset": ""
  },
  "link_color": "#ce9933",
  "link_hover_color": "#274253",
  "list_style": "style_7",
  "p_line_height": "24",
  "p_margin_bottom": "25"
}';
	return $json;
}